name: Build and push docker image
on:
  workflow_dispatch:
  push:
    branches: [main]
  pull_request:
env:
  CARGO_TERM_COLOR: always
jobs:
  get-version:
    runs-on: ubuntu-24.04
    outputs:
      version: ${{ steps.make_version.outputs.version }}
    steps:
      - uses: actions/checkout@v7
        with:
          fetch-depth: 0
      - id: make_version
        run: echo "version=$(date --utc +%Y%m%d)-$(git rev-list ${{ github.sha }} --count)" >> "$GITHUB_OUTPUT"
  build:
    uses: docker/github-builder/.github/workflows/build.yml@v1
    needs: [get-version]
    permissions:
      contents: read # to fetch the repository content
      id-token: write # for signing attestation(s) with GitHub OIDC Token
      packages: write # to push to ghcr
    with:
      context: ./
      push: ${{ github.event_name != 'pull_request' }}
      platforms: linux/amd64,linux/arm64
      cache: true
      cache-mode: max
      output: image
      meta-images: ghcr.io/svix/openapi-codegen
      meta-flavor: |
        latest=${{ github.event_name != 'pull_request' }}
      meta-tags: |
        type=raw,value=${{needs.get-version.outputs.version}}
      set-meta-labels: true
      labels: |
        org.opencontainers.image.version=${{ needs.get-version.outputs.version }}
        org.opencontainers.image.revision=${{ github.sha }}
    secrets:
      registry-auths: |
        - registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
